### PR TITLE
Setup for PyPi

### PR DESCRIPTION
**Pull request by dmarcoux**
As I said, it's the first time I create a package for PyPi. I used another project of yours (`buku`) as a start for `setup.py` and adapted it.

I pushed this to `test.pypi.org` to test the package. It is successfully pushed to `test.pypi.org`, but after installing the package, it doesn't work when executing the `pdd` command. I get the following error:

```
Traceback (most recent call last):
  File "/home/dmarcoux/.local/bin/pdd", line 7, in <module>
    from pdd import main
ModuleNotFoundError: No module named 'pdd'
```

So something is wrong, but I don't know what.

### CODE REVIEW

**Comment by jarun** [comment]
Sorry, my knowledge in PyPi is very very limited. @rachmadaniHaryono any ideas?

**Comment by rachmadaniHaryono** [comment]
Possibility 

- file extension
- packages key on setup

**Comment by dmarcoux** [comment]
It was indeed the missing file extension. Thank you @rachmadaniHaryono!

**Comment by jarun** [comment]
@dmarcoux I am adding you as a collaborator so you can handle the PyPi stuff for `pdd`.

**Pull request merged**
