### PR TITLE
Add zsh completion (rewrite)

### PR DESCRIPTION
**Pull request by Freed-Wu**
1. `cp pdd pdd.py`
2. `scripts/zsh_completion.py`
3. `sudo mv _pdd /usr/share/zsh/site-functions`
4. `compinit`

Because file `pdd` extension is not `.py`, so I cannot `import pdd`. In #21, I
rename `pdd` to `pdd.py` to solve this problem. However, it makes all test
failed. Now I advise `cp pdd pdd.py` to solve this problem. Thanks.

BTW. I notice many files have shebang but don't have executable mode. I advise `chmod +x` for them.

### CODE REVIEW

**Comment by jarun** [comment]
Take a look at the completion script for googler: https://github.com/jarun/googler

**Comment by Freed-Wu** [comment]
Did you mean the completion scripts should be in a directory named `auto-completion/shellname`? I know various programs sometimes use various directory names to contain completion scripts, such as `contrib`, `third-party`, `scripts`, `devscript`. It is not a big problem. :smile: I will do.

Add googler use a writed shell completion script. However, it is not convenient to maintain. I think a good method is to get the `argparser.ArgumentParser`, use it to generate shell completion script automatically. Some programs like `youtube-dl` also do by this method. You can take a look at <https://github.com/ytdl-org/youtube-dl/blob/master/devscripts>:

```
❯ cd devscripts
❯ ls *-completion.*
bash-completion.in  bash-completion.py  fish-completion.in  fish-completion.py  zsh-completion.in  zsh-completion.py
```

How about it?

**Comment by jarun** [comment]
It would be great to have a single python script that can take an argument (or list of arguments like `bash zsh fish`) and generate the script.

**Comment by Freed-Wu** [comment]
> It would be great to have a single python script that can take an argument (or list of arguments like `bash zsh fish`) and generate the script.

I think it is more convenient, because some code can be used repeatedly. However, I never use other shell, so it should wait other shells' user to join this discussion.

BTW, now it is WIP, I will sign when it is finished.

**Comment by jarun** [comment]
Sure!

**Comment by Freed-Wu** [comment]
Now it can work. And I write some examples in docstring to demonstrate how it can work.

```shell
❯ pdd <TAB>
keywords
❯ pdd -<TAB>
keywords
option
--add    add to date (/today) or time (/now)
-c       start a countdown timer
...
❯ pdd -s <TAB>
resolution
1  2  3  4  5  6  7  8  9
❯ pdd -r <TAB>
command
external command
parameter
7za                                 A file archiver with highest compression ratio
...
❯ pdd -d <TAB>
yyyy
❯ pdd -d 2021 Jul <TAB>
dd
❯ pdd -d 2021 Jul 11 2021 Jul 11 <TAB>
keywords
```

**Comment by Freed-Wu** [comment]
Don't forget to add some documentation about it. :smile:

**Comment by jarun** [comment]
I thought you were going to add a script which can generate completion scripts for zsh, bash and fish shells. Is the current PR only for zsh?

**Comment by Freed-Wu** [comment]
> Is the current PR only for zsh?

Right.

> And I write some examples in docstring to demonstrate how it can work.

Only zsh, although I think it is useful for other shells' users to refer (get actions from parser, then generate shell completion script from the actions)

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
> What is the command to generate the zsh completion script?

Ignore. Saw the notes in the script.

**Comment by Freed-Wu** [comment]
> It would be great to have a single python script that can take an argument (or list of arguments like bash zsh fish) and generate the script.

I think `shtab` may be your needed method? Its core only have one script, can be copyed to any other project. And it can support `XXX --print-completion (bash|zsh|tcsh)` and fish/posh in plan. However it only support `nargs={0,1}` by nature, except you write some complex function in `PREAMBLE`.

**Comment by jarun** [comment]
Thanks for the info.

**Pull request merged**
