### PR TITLE
Remove unneeded code to copy pdd to pdd.py

### PR DESCRIPTION
**Pull request by dmarcoux**
pdd.py is a symbolic link to pdd. Without pdd.py, the following warning
in displayed when running `python setup sdist`:

file pdd.py (for module pdd) not found

### CODE REVIEW

**Comment by dmarcoux** [comment]
I tested it on test.pypi and also with the openSUSE package, it works.

To be completely honest, I believe the commit https://github.com/jarun/pdd/commit/c41c5683dd0bd9766feaccc5fa257426ffd12bc7 should be reverted as it isn't following Python standards when it comes to packaging. This makes the unusual changes included in this PR necessary.

What is the advantage of having `pdd` over `pdd.py`? I want to understand the reasoning behind the changes.

**Comment by jarun** [comment]
We can't have both `pdd` and `pdd.py` in the repo. That would be very confusing.

Take a look at [ddgr](https://github.com/jarun/ddgr). We have it on PyPi as well as on openSUSE Leap.

These utilities have very minimal dependencies and can be installed standalone easily. Which is why we didn't take a _Pythonic_ route to get `ddgr` on PyPi.

**Comment by jarun** [comment]
In the worst case, if we can't be on openSUSE without this change, let's drop packaging for openSUSE. People can install `pdd` from PyPi anyway.

**Comment by dmarcoux** [comment]
I will check the `ddgr` package and see what I can do to make it work too for `pdd`. Thank you for your feedback @jarun. I will close this PR and ping you whenever I have something for openSUSE. I will do it in the following days.

**Pull request closed without merging**
